const PHOTO_COUNT = 25;

const MIN_MESSAGE_COUNT = 1;
const MAX_MESSAGE_COUNT = 2;

const HASHTAGS_DELIMITER = ' ';
const HASHTAGS_MAX_COUNT = 5;
const DESCRIPTION_MAX_LENGTH = 140;

const COMMENTS_TO_SHOW_COUNT = 5;

const CONTROL_MAX_VALUE = 100;
const CONTROL_MIN_VALUE = 25;
const CONTROL_STEP = 25;
const CONTROL_DEFAULT_VALUE = 100;

const EFFECT_CLASS_START = 'effects__preview--';

export {
  PHOTO_COUNT,
  MIN_MESSAGE_COUNT,
  MAX_MESSAGE_COUNT,
  HASHTAGS_DELIMITER,
  HASHTAGS_MAX_COUNT,
  DESCRIPTION_MAX_LENGTH,
  COMMENTS_TO_SHOW_COUNT,
  CONTROL_MAX_VALUE,
  CONTROL_MIN_VALUE,
  CONTROL_STEP,
  CONTROL_DEFAULT_VALUE,
  EFFECT_CLASS_START
};
